export type Supplier = {
  id: number;
  name: string;
  fantasyName: string;
  active: number;
  emailAddress: string;
  cpfCnpj: string;
  personType: string;
  stateRegistration: string;
  zipCode: string;
  address: string;
  district: string;
  city: string;
  state: string;
  phoneNumber: string;
  cellNumber: string;
  contactPerson: string;
  obs: string;
  registrationDate: string;
};
